const tourList = [
  {
    name: "SG - Mỹ Tho - Bến Tre",
    slug: "sg-my-tho-ben-tre",
    duration: "1 ngày",
    price: 1000000,
    discountPrice: 500000,
    departureDateTime: null,
    hotelStars: null,
    departurePoint: "TP. Hồ Chí Minh",
    departureSchedule: "Mỗi ngày",
    type: "Ghép đoàn",
    image: "my-tho.jpg"
  },
  {
    name: "SG - Cồn Chim (Trà Vinh)",
    slug: "sg-con-chim",
    duration: "1 ngày",
    price: 1490000,
    discountPrice: 990000,
    departureDateTime: null,
    hotelStars: null,
    departurePoint: "TP. Hồ Chí Minh",
    departureSchedule: "Thứ 7 và Chủ nhật hàng tuần",
    type: "Ghép đoàn",
    note: "Giá tùy số lượng khách",
    image: "con-chim.jpg"
  },
  {
    name: "SG - Trà Vinh - Bảo Tàng Dừa Sáp",
    slug: "sg-tra-vinh-bao-tang",
    duration: "1 ngày",
    price: 1350000,
    discountPrice: 850000,
    departureDateTime: null,
    hotelStars: null,
    departurePoint: "TP. Hồ Chí Minh",
    departureSchedule: "Chủ nhật hàng tuần",
    type: "Ghép đoàn",
    note: "Giá tùy số lượng khách",
    image: "bao-tang.jpg"
  },
  {
    name: "SG - Mỹ Tho - Bến Tre - Cần Thơ",
    slug: "2n-1d-sg-my-tho-ben-tre-can-tho",
    duration: "2 ngày 1 đêm",
    price: 2100000,
    discountPrice: 1600000,
    departureDateTime: null,
    hotelStars: null,
    departurePoint: "TP. Hồ Chí Minh",
    departureSchedule: "Mỗi ngày",
    type: "Ghép đoàn",
    image: "cho-noi.jpg"
  },
  {
    name: "SG - Cần Thơ - Chợ nổi Cái Răng - Cồn Sơn",
    slug: "sg-can-tho-cho-noi-con-son",
    duration: "2 ngày 1 đêm",
    price: 2690000,
    discountPrice: 2190000,
    departureDateTime: null,
    hotelStars: null,
    departurePoint: "TP. Hồ Chí Minh",
    departureSchedule: "Thứ 2, 4, 6, 7 hàng tuần",
    type: "Ghép đoàn",
    image: "cheo-suong.jpg"
  },
  {
    name: "Mỹ Tho - Bến Tre - Cần Thơ - Cà Mau - Bạc Liêu - Sóc Trăng",
    slug: "my-tho-ben-tre-can-tho-ca-mau-bac-lieu-soc-trang",
    duration: "3 ngày 2 đêm",
    price: 3580000,
    discountPrice: 3080000,
    departureDateTime: null,
    hotelStars: null,
    departurePoint: "TP. Hồ Chí Minh",
    departureSchedule: "Thứ 3 và Thứ 6 hàng tuần",
    type: "Ghép đoàn",
    image: "mui-ca-mau.jpg"
  },
  {
    name: "Mỹ Tho - Bến Tre - Châu Đốc - Chùa Bà - Rừng Tràm Trà Sư - Cần Thơ - Cà Mau - Bạc Liêu - Sóc Trăng",
    slug: "4n-3d-my-tho-ben-tre-chau-doc-chua-ba",
    duration: "4 ngày 3 đêm",
    price: 4880000,
    discountPrice: 4380000,
    departureDateTime: null,
    hotelStars: null,
    departurePoint: "TP. Hồ Chí Minh",
    departureSchedule: "Thứ 2 và Thứ 5 hàng tuần",
    type: "Ghép đoàn",
    image: "rung-tram.jpg"
  }
];